
name: Build resume

permissions:
  contents: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make release directory
        run: mkdir -p release

      - name: Make .html
        uses: docker://pandoc/core
        with:
          args: source.md --css style.css -o release/CV.html

      - name: Make .docx
        uses: docker://pandoc/core
        with:
          args: source.md -o release/CV.docx

      - name: Make .md
        uses: docker://pandoc/core
        with:
            args: source.md -o tmp.md -t markdown_strict
      - run: cat name.txt tmp.md > release/CV.md
      - run: rm tmp.md

      - name: Make .pdf
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: CV.html
          outputFile: release/CV.pdf
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.COMMIT_SHORT_SHA }}
          release_name: CV
          body: |
            This is the release of my CV.
            You can find the files in the release section.
          prerelease: true
          files: release/*