
name: Build resume

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  CITE_ARGS: --citeproc --bibliography=references.bib --csl=IEEE_cv.csl

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make release directory
        run: mkdir -p release

      - name: Make .html
        uses: docker://pandoc/core
        with:
          args: source.md --css style.css --embed-resources --standalone ${{ env.CITE_ARGS }} -o release/CV.html

      - name: Make .docx
        uses: docker://pandoc/core
        with:
          args: source.md ${{ env.CITE_ARGS }} -o release/CV.docx

      - name: Make .md
        uses: docker://pandoc/core
        with:
            args: source.md -o tmp.md -t markdown_strict ${{ env.CITE_ARGS }}
      - run: cat name.txt tmp.md > release/CV.md
      - run: rm tmp.md

      - uses: browser-actions/setup-chrome@v1
        id: setup-chrome

      - name: Make .pdf
        run: |
          ${{ steps.setup-chrome.outputs.chrome-path }} \
          --headless --disable-gpu --no-sandbox \
          --print-to-pdf=$GITHUB_WORKSPACE/release/CV.pdf \
          --print-to-pdf-no-header \
          --no-pdf-header-footer \
          --virtual-time-budget=10000 \
          file://$GITHUB_WORKSPACE/release/CV.html

      # Upload the assets to the release
      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          name: CV
          body: |
            This is the release of my CV.
            You can find the files in the release section.
          files: release/*